export const MINING_RARITY_ORDER = [
  'legendary',
  'epic',
  'rare',
  'uncommon',
  'common',
  'handMineable',
] as const

export const ORE_SIGNATURES: Record<string, number> = {
  Quantainium: 3170,
  Stileron: 3185,
  Savrilium: 3200,
  Ouratite: 3370,
  Riccite: 3385,
  Lindinium: 3400,
  Beryl: 3540,
  Taranite: 3555,
  Borase: 3570,
  Gold: 3585,
  Bexalite: 3600,
  Laranite: 3825,
  Aslarite: 3840,
  Titanium: 3855,
  Tungsten: 3870,
  Agricium: 3885,
  Torite: 3900,
  Hephestanite: 4180,
  Tin: 4195,
  Quartz: 4210,
  Corundum: 4225,
  Copper: 4240,
  Silicon: 4255,
  Iron: 4270,
  Aluminium: 4285,
  Ice: 4300,
}

export const LOCATION_SYSTEMS: Record<string, string> = {
  Aberdeen: 'Stanton',
  Arial: 'Stanton',
  Hurston: 'Stanton',
  Yela: 'Stanton',
  'Yela Ring': 'Stanton',
  Daymar: 'Stanton',
  Cellin: 'Stanton',
  Wala: 'Stanton',
  Magda: 'Stanton',
  Clio: 'Stanton',
  Calliope: 'Stanton',
  Euterpe: 'Stanton',
  Lyria: 'Stanton',
  'Aaron Halo': 'Stanton',
  'ARC-L1': 'Stanton',
  'ARC-L2': 'Stanton',
  'ARC-L3': 'Stanton',
  'ARC-L4': 'Stanton',
  'ARC-L5': 'Stanton',
  'CRU-L1': 'Stanton',
  'CRU-L2': 'Stanton',
  'CRU-L3': 'Stanton',
  'CRU-L4': 'Stanton',
  'CRU-L5': 'Stanton',
  'HUR-L1': 'Stanton',
  'HUR-L2': 'Stanton',
  'HUR-L3': 'Stanton',
  'HUR-L4': 'Stanton',
  'HUR-L5': 'Stanton',
  'MIC-L1': 'Stanton',
  'MIC-L2': 'Stanton',
  'MIC-L3': 'Stanton',
  'MIC-L4': 'Stanton',
  'MIC-L5': 'Stanton',
  Adir: 'Pyro',
  Bloom: 'Pyro',
  Fairo: 'Pyro',
  Fuego: 'Pyro',
  Ignis: 'Pyro',
  Terminus: 'Pyro',
  Vatra: 'Pyro',
  Vuur: 'Pyro',
  'Pyro IV': 'Pyro',
  'Akiro Cluster': 'Pyro',
  'Glaciem Ring': 'Pyro',
  'Keeger Belt': 'Pyro',
  'Pyro Asteroid Clusters': 'Pyro',
  'All Pyro Planets': 'Pyro',
  'QV Breaker Stations (Nyx)': 'Nyx',
  'Found in All Stanton Deposits': 'Stanton',
}

export const MINING_SYSTEM_COLORS: Record<string, string> = {
  Stanton: 'text-blue-400',
  Pyro: 'text-orange-400',
  Nyx: 'text-purple-400',
}

export const MINING_RARITY_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  legendary: { bg: 'bg-amber-500/10', text: 'text-amber-400', border: 'border-amber-500/30' },
  epic: { bg: 'bg-purple-500/10', text: 'text-purple-400', border: 'border-purple-500/30' },
  rare: { bg: 'bg-blue-500/10', text: 'text-blue-400', border: 'border-blue-500/30' },
  uncommon: { bg: 'bg-green-500/10', text: 'text-green-400', border: 'border-green-500/30' },
  common: { bg: 'bg-slate-500/10', text: 'text-slate-400', border: 'border-slate-500/30' },
  handMineable: { bg: 'bg-cyan-500/10', text: 'text-cyan-400', border: 'border-cyan-500/30' },
}

export const MINING_RARITY_LABELS: Record<string, string> = {
  legendary: 'Legendary',
  epic: 'Epic',
  rare: 'Rare',
  uncommon: 'Uncommon',
  common: 'Common',
  handMineable: 'Hand Mineable',
}
