#!/usr/bin/env python3
"""
Import blueprints JSON export to your account via Supabase Edge Function.
Works on macOS, Windows, and Linux. Requires Python 3.
"""

import argparse
import json
import os
import sys
from pathlib import Path

try:
    import requests
except ImportError:
    print("Error: The 'requests' library is not installed. Run 'pip install -r requirements.txt' first.", file=sys.stderr)
    sys.exit(1)

# ANSI colors for nice terminal feedback
class Colors:
    GREEN = "\033[92m"
    CYAN = "\033[96m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    DIM = "\033[2m"
    RESET = "\033[0m"

def disable_colors():
    """No-op colors for environments that do not support them."""
    Colors.GREEN = ""
    Colors.CYAN = ""
    Colors.YELLOW = ""
    Colors.RED = ""
    Colors.DIM = ""
    Colors.RESET = ""

def main():
    # Disable color codes on Windows if color initialization isn't supported, or if stdout is redirected
    if sys.platform == "win32":
        try:
            import ctypes
            kernel32 = ctypes.windll.kernel32
            # Enable ANSI escape processing
            kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
        except Exception:
            disable_colors()
    if not sys.stdout.isatty():
        disable_colors()

    parser = argparse.ArgumentParser(
        description="Submit historical log-watcher blueprint exports to your account."
    )
    parser.add_argument(
        "file_path",
        type=Path,
        help="Path to the JSON file generated by 'watcher.py import'"
    )
    parser.add_argument(
        "--url",
        required=True,
        help="Supabase log-watcher-webhook Edge Function URL (e.g. https://<project>.supabase.co/functions/v1/log-watcher-webhook)"
    )
    parser.add_argument(
        "--key",
        help="Your secret API key. If omitted, the script will read the LOG_WATCHER_API_KEY environment variable."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Dry run: scan and log blueprints locally without making network calls or requiring an API key."
    )

    args = parser.parse_args()

    # Resolve API Key (only required if not performing a dry run)
    api_key = None
    if not args.dry_run:
        api_key = args.key or os.getenv("LOG_WATCHER_API_KEY")
        if not api_key:
            print(f"{Colors.RED}Error: API key must be provided via --key or LOG_WATCHER_API_KEY environment variable.{Colors.RESET}", file=sys.stderr)
            sys.exit(1)

    # Validate JSON File
    if not args.file_path.is_file():
        print(f"{Colors.RED}Error: File not found: {args.file_path}{Colors.RESET}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(args.file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"{Colors.RED}Error parsing JSON: {e}{Colors.RESET}", file=sys.stderr)
        sys.exit(1)

    blueprints = data.get("blueprints", [])
    if not blueprints:
        print(f"{Colors.YELLOW}No blueprints found in the export file.{Colors.RESET}")
        return

    # Extract distinct blueprint productNames
    unique_blueprints = sorted(list(set(
        bp.get("productName") for bp in blueprints if bp.get("productName")
    )))

    print(f"{Colors.CYAN}Starting import of {len(unique_blueprints)} unique blueprint(s) from {args.file_path.name}...{Colors.RESET}")
    print()

    success_count = 0
    dupe_count = 0
    fail_count = 0

    if args.dry_run:
        for idx, bp_id in enumerate(unique_blueprints, 1):
            success_count += 1
            print(f"  [{idx}/{len(unique_blueprints)}] {Colors.GREEN}★ Would Import:{Colors.RESET} {bp_id}")
    else:
        session = requests.Session()
        session.headers.update({
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        })

        for idx, bp_id in enumerate(unique_blueprints, 1):
            payload = {
                "type": "blueprint_received",
                "blueprint": bp_id
            }

            try:
                res = session.post(args.url, json=payload, timeout=15)
                response_json = res.json()

                if res.status_code == 200:
                    is_duplicate = response_json.get("duplicate", False)
                    if is_duplicate:
                        dupe_count += 1
                        print(f"  [{idx}/{len(unique_blueprints)}] {Colors.YELLOW}↻ Already Acquired:{Colors.RESET} {bp_id}")
                    else:
                        success_count += 1
                        print(f"  [{idx}/{len(unique_blueprints)}] {Colors.GREEN}★ Successfully Imported:{Colors.RESET} {bp_id}")
                else:
                    fail_count += 1
                    reason = response_json.get("error", f"HTTP {res.status_code}")
                    print(f"  [{idx}/{len(unique_blueprints)}] {Colors.RED}✗ Failed:{Colors.RESET} {bp_id} {Colors.DIM}(Reason: {reason}){Colors.RESET}")

            except requests.RequestException as e:
                fail_count += 1
                print(f"  [{idx}/{len(unique_blueprints)}] {Colors.RED}✗ Connection Error:{Colors.RESET} {bp_id} {Colors.DIM}(Reason: {e}){Colors.RESET}")

    print()
    print(f"{Colors.CYAN}Import Finished Summary:{Colors.RESET}")
    if args.dry_run:
        print(f"  {Colors.GREEN}★ Would Import: {success_count}{Colors.RESET}")
    else:
        print(f"  {Colors.GREEN}★ Imported:     {success_count}{Colors.RESET}")
        print(f"  {Colors.YELLOW}↻ Duplicates:   {dupe_count}{Colors.RESET}")
        if fail_count > 0:
            print(f"  {Colors.RED}✗ Failed:       {fail_count}{Colors.RESET}")
        else:
            print(f"  ✗ Failed:       0")

if __name__ == "__main__":
    main()
