#!/usr/bin/env python3
"""
Import blueprints JSON export to the database via Supabase Edge Function.
Works on macOS, Windows, and Linux. Requires Python 3.
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

# ANSI colors for nice terminal feedback
class Colors:
    GREEN = "\033[92m"
    CYAN = "\033[96m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    DIM = "\033[2m"
    RESET = "\033[0m"

def disable_colors():
    """No-op colors for environments that do not support them."""
    Colors.GREEN = ""
    Colors.CYAN = ""
    Colors.YELLOW = ""
    Colors.RED = ""
    Colors.DIM = ""
    Colors.RESET = ""

def main():
    # Disable color codes on Windows if color initialization isn't supported, or if stdout is redirected
    if sys.platform == "win32":
        try:
            import ctypes
            kernel32 = ctypes.windll.kernel32
            # Enable ANSI escape processing
            kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
        except Exception:
            disable_colors()
    if not sys.stdout.isatty():
        disable_colors()

    parser = argparse.ArgumentParser(
        description="Submit historical log-watcher blueprint exports to your account."
    )
    parser.add_argument(
        "file_path",
        type=Path,
        help="Path to the JSON file generated by 'watcher.py import'"
    )
    parser.add_argument(
        "--url",
        required=True,
        help="Supabase log-watcher-webhook Edge Function URL (e.g. https://<project>.supabase.co/functions/v1/log-watcher-webhook)"
    )
    parser.add_argument(
        "--key",
        help="Your secret API key. If omitted, the script will read the SCMDB_API_KEY environment variable."
    )

    args = parser.parse_args()

    # Resolve API Key
    api_key = args.key or os.getenv("SCMDB_API_KEY")
    if not api_key:
        print(f"{Colors.RED}Error: API key must be provided via --key or SCMDB_API_KEY environment variable.{Colors.RESET}", file=sys.stderr)
        sys.exit(1)

    # Validate JSON File
    if not args.file_path.is_file():
        print(f"{Colors.RED}Error: File not found: {args.file_path}{Colors.RESET}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(args.file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"{Colors.RED}Error parsing JSON: {e}{Colors.RESET}", file=sys.stderr)
        sys.exit(1)

    blueprints = data.get("blueprints", [])
    if not blueprints:
        print(f"{Colors.YELLOW}No blueprints found in the export file.{Colors.RESET}")
        return

    # Extract distinct blueprint productNames
    unique_blueprints = sorted(list(set(
        bp.get("productName") for bp in blueprints if bp.get("productName")
    )))

    print(f"{Colors.CYAN}Starting import of {len(unique_blueprints)} unique blueprint(s) from {args.file_path.name}...{Colors.RESET}")
    print()

    success_count = 0
    dupe_count = 0
    fail_count = 0

    for idx, bp_id in enumerate(unique_blueprints, 1):
        payload = json.dumps({
            "type": "blueprint_received",
            "blueprint": bp_id
        }).encode("utf-8")

        req = urllib.request.Request(
            args.url,
            data=payload,
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            },
            method="POST"
        )

        try:
            with urllib.request.urlopen(req) as res:
                response_data = json.loads(res.read().decode("utf-8"))
                
                is_duplicate = response_data.get("duplicate", False)
                if is_duplicate:
                    dupe_count += 1
                    print(f"  [{idx}/{len(unique_blueprints)}] {Colors.YELLOW}↻ Already Acquired:{Colors.RESET} {bp_id}")
                else:
                    success_count += 1
                    print(f"  [{idx}/{len(unique_blueprints)}] {Colors.GREEN}★ Successfully Imported:{Colors.RESET} {bp_id}")
        except urllib.error.HTTPError as e:
            fail_count += 1
            error_msg = e.read().decode("utf-8")
            try:
                error_json = json.loads(error_msg)
                reason = error_json.get("error", "Unknown API error")
            except Exception:
                reason = error_msg or f"HTTP {e.code}"
            print(f"  [{idx}/{len(unique_blueprints)}] {Colors.RED}✗ Failed:{Colors.RESET} {bp_id} {Colors.DIM}(Reason: {reason}){Colors.RESET}")
        except Exception as e:
            fail_count += 1
            print(f"  [{idx}/{len(unique_blueprints)}] {Colors.RED}✗ Connection Error:{Colors.RESET} {bp_id} {Colors.DIM}(Reason: {e}){Colors.RESET}")

    print()
    print(f"{Colors.CYAN}Import Finished Summary:{Colors.RESET}")
    print(f"  {Colors.GREEN}★ Imported:    {success_count}{Colors.RESET}")
    print(f"  {Colors.YELLOW}↻ Duplicates:  {dupe_count}{Colors.RESET}")
    if fail_count > 0:
        print(f"  {Colors.RED}✗ Failed:      {fail_count}{Colors.RESET}")
    else:
        print(f"  ✗ Failed:      0")

if __name__ == "__main__":
    main()
